Added Ecuador ID (IC) validator
reducktion/socrates pull request #104
Opened 2020-10-12 23:13 UTC by gheleri

resolve #103 
It includes the validator and unit tests.

2020-10-13 09:44 UTC, AlexOlival requested changes
Just two small tidbits. Great work again :hugs: 
Are there not many extractors in the Americas? That's a shame :stuck_out_tongue:

2020-10-13 09:44 UTC, AlexOlival commented on src/Core/SouthAmerica/Ecuador/EcuadorIdValidator.php
> +        $thirdDigit = (int)substr($id, 2, 1);
If we're plucking a single digit, we can use PHP's array access (which I dearly miss in other languages :zany_face:)

2020-10-13 09:44 UTC, AlexOlival commented on src/Core/SouthAmerica/Ecuador/EcuadorIdValidator.php
> +        $result = $remaining !== 0 ? 10 - $remaining : 0;
"remainder" is more appropriate here

2020-10-13 10:57 UTC, gheleri commented
> Are there not many extractors in the Americas? That's a shame

There're no rules in no man's land :P. Some countries are nearly impossible to get some info about IDs on internet

2020-10-13 12:14 UTC, AlexOlival approved these changes

2020-10-16 08:46 UTC, JoaoFSCruz approved these changes

2020-10-16 10:39 UTC, merged