feat: Mexican ID Validator
reducktion/socrates pull request #78
Opened 2020-10-08 01:36 UTC by tiagomichaelsousa

This PR will allow the validation for the Mexican identification number, aka CURP.

All the information to write the validators can be found [here](https://sayari.com/blog/breaking-down-mexican-national-id/).

If you guys have any suggestions feel free.

Feat from: #71 

**More info about CURP:**
- https://formvalidation.io/guide/validators/id/mexican-identification-number/
- http://sistemas.uaeh.edu.mx/dce/admisiones/docs/guia_CURP.pdf
- https://en.wikipedia.org/wiki/Unique_Population_Registry_Code

2020-10-08 18:31 UTC, JoaoFSCruz requested changes
Thank you for your PR! It's great to see more people contributing 🎉 

There are some issues which are commented along with the code. Just a small recap with a couple more issues:
- Order alphabetically the validator class declaration in the config file
- Keep the validation logic inside the MexicoIdValidator class (stick with the structure all the other countries already follow)
- Framework related functions/features/wtv are not welcomed in the core (compatibility issues)
- Insufficient test cases
- The Mexico Id supports extraction, maybe just make one more small effort and implement it too 😅 
- Target the 1.2 (soon to be changed to 1.3) branch

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/Constants/Vowels.php
> +class Vowels
There is no need in creating a class to just return vowels. It won't be reused enough times to make sense in creating one. I suggest to merge it with the MexicoIdValidator class.

Keep it simple stupid (K.I.S.S. 💋)

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/MexicoIdValidator.php
> +use Facades\Reducktion\Socrates\Core\Mexico\Validators\Gender as GenderValidator;
This is a vanilla PHP package that provides a Facade and a Validation Rule to be used by Laravel applications. The core cannot use functions or anything from any framework whatsoever. Let's keep the package framework agnostic, shall we? 😃

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/Validators/Birthdate.php
> +class Birthdate implements IdValidator
As I said before, keep it simple. Merge with the MexicoIdValidator since it won't be used again.

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/Validators/Checksum.php
> +class Checksum implements IdValidator
Ditto ☝️

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/Validators/Consoants.php
> +class Consoants implements IdValidator
Ditto ☝️

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/Validators/Gender.php
> +    public function validate(string $gender): bool
Ditto ☝️

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/Validators/Names.php
> +    public function validate(string $names): bool
Ditto ☝️

2020-10-08 18:31 UTC, JoaoFSCruz commented on src/Core/Mexico/Validators/State.php
> +class State implements IdValidator
The states array should be extracted to a file (like [Italy)](https://github.com/reducktion/socrates/tree/master/src/Core/Italy) and each state should get the name added not just the state code.

Besides that, merge with MexicoIdValidator as said above.

2020-10-08 18:31 UTC, JoaoFSCruz commented on tests/Feature/MexicoTest.php
> +class MexicoTest extends FeatureTest
Add more test cases. I know it's not easy to get valid ids, but we have to get as much as we can to rely on our tests.

At least 5 valid ids and 5 invalid ids.

2020-10-08 21:55 UTC, AlexOlival requested changes
Looking good so far! Just two minor things on the validator and I think we're ok there.
Do you mind also implementing an extractor, given that this ID encodes personal information?

2020-10-08 21:55 UTC, AlexOlival commented on src/Core/Mexico/MexicoIdValidator.php
> +    const CURP_SIZE = 18;
I think we can lose this constant safely

2020-10-08 21:55 UTC, AlexOlival commented on src/Core/Mexico/MexicoIdValidator.php
> +    private function validateConsoants(string $names): bool
Little typo here, *consonants

2020-10-08 23:37 UTC, tiagomichaelsousa commented
> Looking good so far! Just two minor things on the validator and I think we're ok there.
> Do you mind also implementing an extractor, given that this ID encodes personal information?

Sure 🙂

2020-10-08 23:39 UTC, tiagomichaelsousa commented on src/Core/Mexico/MexicoIdValidator.php
> +    private function validateConsoants(string $names): bool
Nice 👀 Thank you!

2020-10-09 10:21 UTC, AlexOlival requested changes
One final request: change all references of `intval` to a cast to int.
This is because [casting to int is faster now](http://tonyshowoff.com/articles/casting-int-faster-than-intval-in-php/).

One way to detect these kinds of improvements is to use EA Extended Inspections plugin on PHPStorm. Highly recommend :+1:

2020-10-09 13:47 UTC, AlexOlival commented
I have fixed the branch name because it was erroneously targetting a tag.
Please change the merge target to release-1.3.0

2020-10-10 00:50 UTC, tiagomichaelsousa commented
> e the merge target

I think everything is okay now!  If not, please let me know 🙂

2020-10-10 00:50 UTC, tiagomichaelsousa commented
> I have fixed the branch name because it was erroneously targetting a tag.
> Please change the merge target to release-1.3.0

I think everything is okay now! If not, please let me know 🙂

2020-10-10 13:39 UTC, AlexOlival requested changes
Final little touches

2020-10-10 13:39 UTC, AlexOlival commented on src/Config/Countries.php
> +         * Validators for north american countries.
Typo in this comment

2020-10-10 13:39 UTC, AlexOlival commented on src/Core/NorthAmerica/Mexico/MexicoCitizenInformationExtractor.php
> +        if ($identifier === MexicoIdValidator::GENDERS[0]) {
I'd prefer if you use the actual value here, rather than another reference to the validator class

2020-10-10 13:39 UTC, AlexOlival commented on tests/Feature/NorthAmerica/MexicoTest.php
> +        ];
Are these mexican names? :sweat_smile:

2020-10-10 13:39 UTC, AlexOlival commented on tests/Feature/NorthAmerica/MexicoTest.php
> +    private $MEXICO_CODE = 'MX';
We can go ahead and inline this as well, to make it similar to the other tests

2020-10-10 17:54 UTC, tiagomichaelsousa commented
> Final little touches

Fixed 🙂

2020-10-10 19:18 UTC, AlexOlival commented
Will merge asap when I'm back on the computer to call in the contributor bot

2020-10-11 11:07 UTC, AlexOlival commented
Cheers @tiagomichaelsousa 🙏 
I might tweak the validator a little bit to make it more inline with the other classes, but that'll come later

@all-contributors please add @tiagomichaelsousa for code and documentation

2020-10-11 11:07 UTC, merged