Added Chile ID (RUT) validator
reducktion/socrates pull request #81
Opened 2020-10-08 19:25 UTC by gheleri

resolve #79
It includes the validator itself and unit tests. The algorithm was based on wikipedia info.

2020-10-08 22:00 UTC, AlexOlival requested changes
Looking great here as well! Just a minor alphabetic order issue. Also, please target the v1.2.0 branch.

Thank you!

2020-10-08 22:25 UTC, AlexOlival commented
You'll have to fix the conflicts. We're now namespacing by continent, so make sure to get those right!

2020-10-08 22:29 UTC, gheleri commented
Should I namespace as Latin America or Central/South America? Latin America seems easiest

2020-10-08 22:34 UTC, gheleri commented
> You'll have to fix the conflicts. We're now namespacing by continent, so make sure to get those right!

Should I namespace as Latin America or Central/South America? Latin America seems easiest

2020-10-08 22:41 UTC, gheleri commented
Please check now

2020-10-08 23:14 UTC, AlexOlival commented
I think Geography makes more sense here, so SouthAmerica 👍

2020-10-08 23:25 UTC, gheleri commented
It's done, mate!

2020-10-09 10:22 UTC, AlexOlival approved these changes

2020-10-09 10:22 UTC, AlexOlival commented
Looking good on my end :+1: 
Just needs @JoaoFSCruz to take a look

2020-10-09 10:43 UTC, JoaoFSCruz requested changes
Wonderful job!!! Just two small changes regarding the sources. Thank you for your contribution 🙏

2020-10-09 10:43 UTC, JoaoFSCruz commented on src/Core/SouthAmerica/Brazil/BrazilIdValidator.php
> +        // source: https://pt.wikipedia.org/wiki/Cadastro_de_pessoas_f%C3%ADsicas#Algoritmo
Although it's not done in every country implementation (my bad 😞), add a docblock for the class to include the source of the algorithm (here is an [example](https://github.com/reducktion/socrates/blob/master/src/Core/Portugal/PortugalIdValidator.php)).

2020-10-09 10:43 UTC, JoaoFSCruz commented on src/Core/SouthAmerica/Chile/ChileIdValidator.php
> +        // source: https://es.wikipedia.org/wiki/Anexo:Implementaciones_para_algoritmo_de_rut
Ditto as above.

2020-10-09 13:47 UTC, AlexOlival commented
I have fixed the branch name because it was erroneously targetting a tag.
Please change the merge target to release-1.3.0

2020-10-09 14:10 UTC, AlexOlival commented on src/Core/SouthAmerica/Brazil/BrazilIdValidator.php
> +        // source: https://pt.wikipedia.org/wiki/Cadastro_de_pessoas_f%C3%ADsicas#Algoritmo
This isn't scoped to him, but if he can go ahead and change this after targetting the new `release-1.3.0` branch, we'd be much appreciated :pray:

2020-10-09 17:01 UTC, gheleri commented
Done. I already changed the target to release-1.3.0 and add the codeblocks for Brazil, Chile and others minor fixes. However I did not add the code block for other European countries that do not yet have that (I realized it is necessary to add it when there are comments)

2020-10-09 17:20 UTC, JoaoFSCruz approved these changes
Great! Don't worry about the other docblocks. It's a long long task to be undertaken. As we go we'll add the sources and anything that's needed.

Thank you so much for your contribution 🙏

2020-10-09 17:36 UTC, AlexOlival commented
Valeu @gheleri! 😁
@all-contributors please add @gheleri for code and documentation

2020-10-09 17:37 UTC, merged