Add german TIN validator
reducktion/socrates pull request #97
Opened 2020-10-10 23:24 UTC by bofalke

This PR will implements the Validor for German Tax Identification Number (TIN) mentioned in #47

2020-10-11 11:14 UTC, AlexOlival requested changes
Thank you for your work in this!
I left some comments to be addressed.

2020-10-11 11:14 UTC, AlexOlival commented on src/Core/Europe/Germany/GermanIdValidator.php
> +        $idlength = strLen($id);
I've never seen this function call, does this work? 🤔 
Even if it does, could you change to the common syntax for consistency please?
https://www.php.net/manual/en/function.strlen.php

2020-10-11 11:14 UTC, AlexOlival commented on src/Core/Europe/Germany/GermanIdValidator.php
> +        if (11 !== $idlength) {
Yoda conditions are great, but we haven't been using them. For the sake of consistency let's swap both terms of the statement. Also, please rename the variable to `$idLength`

2020-10-11 11:14 UTC, AlexOlival commented on src/Core/Europe/Germany/GermanIdValidator.php
> +        }
You can keep these, but I think it's fine to inline these operations.
In case you prefer to keep the functions, please change `isDigitsHasCorrectStats` to `checkDigitsHaveCorrectStats` or something more grammatically correct.

I think inlining is still preferable 😛

2020-10-11 11:14 UTC, AlexOlival commented on tests/Feature/Europe/GermanyTest.php
> +        ];
Can we get at least five test cases for each, please?

2020-10-12 07:52 UTC, bofalke commented on tests/Feature/Europe/GermanyTest.php
> +        ];
Yes sure, i found only those three in some documentation thats why i chose them. I made two more up and hope they do not belong to anyone..

2020-10-12 07:53 UTC, bofalke commented on src/Core/Europe/Germany/GermanIdValidator.php
> +        }
Inlined everything :+1:

2020-10-12 07:53 UTC, bofalke commented on src/Core/Europe/Germany/GermanIdValidator.php
> +        $idlength = strLen($id);
It works but was not intended, good catch

2020-10-12 12:38 UTC, AlexOlival approved these changes

2020-10-12 12:38 UTC, AlexOlival commented on src/Core/Europe/Germany/GermanIdValidator.php
> +        if ((9 !== $countDigits && 8 !== $countDigits)) {
Invert these yoda conditions too, please

2020-10-12 12:38 UTC, AlexOlival commented on src/Core/Europe/Germany/GermanIdValidator.php
> +            if (0 === $sum) {
Ditto as above

2020-10-12 12:38 UTC, AlexOlival commented on src/Core/Europe/Germany/GermanIdValidator.php
> +        if (10 === $checksum) {
Ditto

2020-10-12 12:39 UTC, AlexOlival requested changes
Some more small tweaks

2020-10-12 12:39 UTC, AlexOlival commented on tests/Feature/Europe/GermanyTest.php
> +        Socrates::validateId('0123456789', 'GR');
Not the correct country code

2020-10-12 15:31 UTC, AlexOlival approved these changes
We're there! Thank you!
@JoaoFSCruz please come take a looksie.

Also, one last request - but I can take care of that later if you don't feel like it.
Could you change the readme to reflect the fact that we're no longer not supporting Germany?

2020-10-12 18:23 UTC, JoaoFSCruz requested changes
Thank you for your contribution! Nicely done ✔️ 

Just a couple of small things. 
- Please include the source of the algorithm so it's easier to maintain the code
- Update the README.md and Countries.md

2020-10-13 07:39 UTC, bofalke commented
For the source of the algorithm should i link the original repo that i found? Other documentation is mostly in German, so i do not know if that's of any help?

2020-10-13 09:45 UTC, AlexOlival commented
> For the source of the algorithm should i link the original repo that i found? Other documentation is mostly in German, so i do not know if that's of any help?

It's fine if the documentation is in another language. Any (correct) source will do :pray: 
If the documentation is enough, then we don't need to link to any other implementations imo

2020-10-13 09:47 UTC, AlexOlival requested changes
Two small corrections on the markdown changes

2020-10-13 09:47 UTC, AlexOlival commented on COUNTRIES.md
> +| Germany 🇩🇪                |      DE      | :heavy_check_mark: | :x:                |
We need this list to be ordered alphabetically by the country name please

2020-10-13 09:47 UTC, AlexOlival commented on README.md
> +Four european countries are currently unsupported: Austria 🇦🇹, Belarus 🇧🇾 and Cyprus 🇨🇾. This is because we could not find a reliable source for the algorithm, if at all. Help would be appreciated to
Three* :grin:

2020-10-13 12:29 UTC, bofalke commented on README.md
> +Four european countries are currently unsupported: Austria 🇦🇹, Belarus 🇧🇾 and Cyprus 🇨🇾. This is because we could not find a reliable source for the algorithm, if at all. Help would be appreciated to
Ooops :D

2020-10-13 12:44 UTC, bofalke commented
There is an official document by ELSTER (that is the german institute to make your tax declarations online). They have a downloadable pdf where the details are explained in Chapter 2.2.

https://download.elster.de/download/schnittstellen/Pruefung_der_Steuer_und_Steueridentifikatsnummer.pdf

Should I use the download URL  to this PDF or this a problem since download urls tend to disappear sooner or later?

2020-10-13 12:49 UTC, AlexOlival commented
> There is an official document by ELSTER (that is the german institute to make your tax declarations online). They have a downloadable pdf where the details are explained in Chapter 2.2.
> 
> https://download.elster.de/download/schnittstellen/Pruefung_der_Steuer_und_Steueridentifikatsnummer.pdf
> 
> Should I use the download URL to this PDF or this a problem since download urls tend to disappear sooner or later?

It's fine to link to the PDF
That's a risk we're taking with all links - but at least one can derive some information from the URL itself and try to find another source :+1:

2020-10-13 13:03 UTC, bofalke commented
>It's fine to link to the PDF
That's a risk we're taking with all links - but at least one can derive some information from the URL itself and try to find another source :+1: 

Allright, i will link it. 

I just saw that they have some example values as well for the TIN in the documentation, maybe i should use those in our tests as well? 
There is a disclaimer below saying something like:
"The ID was taken from the concept of the Federal Information Technology Center and serves
solely for the purpose of illustrating the implementation. Under no circumstances may the ID be used for test or real transfers!"

I do not want to get you guys in trouble after all. The documentation said that for testing purposes an ID with a leading 0 should be used. I could disable the leading 0 check if the `APP_ENV` is set to `TEST` if you like. Alternatively i could at least use my TIN for the German Test if you like.

2020-10-13 13:36 UTC, AlexOlival commented
> I do not want to get you guys in trouble after all. The documentation said that for testing purposes an ID with a leading 0 should be used. I could disable the leading 0 check if the `APP_ENV` is set to `TEST` if you like. Alternatively i could at least use my TIN for the German Test if you like.

We'll trust the algorithm and we'll trust you :smile: 
In that case you can go ahead and use test IDs which they allow - no need for edge cases

2020-10-13 13:40 UTC, bofalke commented
So i can leave everything like it is? :D Sorry for the confusion

2020-10-13 14:43 UTC, AlexOlival commented
> So i can leave everything like it is? :D Sorry for the confusion

Use invalid IDs that the German authorities allow - whatever is legal

2020-10-13 14:50 UTC, bofalke commented
So i will use testing IDs with a leading 0. That would then cause the test to fail because valid TIN's must not start with a 0. If you like i can at least use my own TIN to have one valid ID in the test.

2020-10-13 14:57 UTC, AlexOlival commented
> So i will use testing IDs with a leading 0. That would then cause the test to fail because valid TIN's must not start with a 0. If you like i can at least use my own TIN to have one valid ID in the test.

Ahhhh I finally understood what you meant... 
Well I'm not a fan of environment variables and workarounds for testing in packages.
I also find it weird that we're not allowed to use IDs when these don't actually encode any information (especially if you used a generator for them)

I say we keep it as it is. If someone asks us to remove them, we will :man_shrugging:

2020-10-13 15:32 UTC, bofalke commented
Ok perfect :+1: So this is all good now? :D

2020-10-13 15:37 UTC, AlexOlival approved these changes

2020-10-13 15:37 UTC, AlexOlival commented
All good from my end!
@JoaoFSCruz como take a looksie

2020-10-13 15:39 UTC, AlexOlival commented
@all-contributors please add @bofalke for documentation

2020-10-16 08:48 UTC, JoaoFSCruz approved these changes

2020-10-16 10:39 UTC, merged