Feat/peru
reducktion/socrates pull request #98
Opened 2020-10-11 10:29 UTC by gheleri

resolve #96 
It includes the validator and unit tests.

2020-10-11 11:20 UTC, AlexOlival requested changes
Thank you! I left some comments for you to address.

2020-10-11 11:20 UTC, AlexOlival commented on src/Core/SouthAmerica/Peru/PeruIdValidator.php
> + * @package Reducktion\Socrates\Core\SouthAmerica\Brazil
Little typo here

2020-10-11 11:20 UTC, AlexOlival commented on src/Core/SouthAmerica/Peru/PeruIdValidator.php
> +        $NumberKeys = [6, 7, 8, 9, 0, 1, 1, 2, 3, 4, 5];
Please use `$camelCase`

2020-10-11 11:20 UTC, AlexOlival commented on src/Core/SouthAmerica/Peru/PeruIdValidator.php
> +        for ($i = 0; $i < count($dniDigits); $i++) {
You're better off caching `count($dniDigits)` in a variable and then using it here for better performance. Otherwise, each iteration calculates the number of digits.

2020-10-11 11:20 UTC, AlexOlival commented on src/Core/SouthAmerica/Peru/PeruIdValidator.php
> +        $key = $key == 11 ? 0 : $key;
Let's use `===` to be extra sure. I might have missed this in your other PRs, can you please take a look? It's fine to push that change in this PR as well, in case you need to change comparisons on other validators.

2020-10-11 11:20 UTC, AlexOlival commented on src/Core/SouthAmerica/Peru/PeruIdValidator.php
> +        }
These can be simplified. Invert some statements to avoid using an `else`

2020-10-11 11:34 UTC, gheleri commented on src/Core/SouthAmerica/Peru/PeruIdValidator.php
> +        for ($i = 0; $i < count($dniDigits); $i++) {
Thanks. I didn't remember that

2020-10-11 12:12 UTC, gheleri commented on src/Core/SouthAmerica/Peru/PeruIdValidator.php
> +        }
Please make a check if the refactor I did is enough for you

2020-10-11 12:14 UTC, gheleri commented
All done. Thanks for the lessons xD

2020-10-11 12:56 UTC, AlexOlival approved these changes

2020-10-11 12:56 UTC, AlexOlival commented
It's looking good from my end!
Just needs @JoaoFSCruz to come take a look

2020-10-12 18:12 UTC, JoaoFSCruz approved these changes
Everything looks fine to me. Great job 🎉

2020-10-12 18:17 UTC, merged